# -*- coding: utf-8 -*-
"""DNA_sequencing_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXjtfCvoYOazKJ16bTDJY6IIheJFlyuo
"""



"""# DNA Sequencing Classification"""

!pip install biopython

"""### DNA data handling using Biopython

Here is a brief example of how to work with a DNA sequence in fasta format using Biopython. The sequence object will contain attributes such as id and sequence and the length of the sequence that you can work with directly.


We will use Bio.SeqIO from Biopython for parsing DNA sequence data(fasta). It provides a simple uniform interface to input and output assorted sequence file formats.
"""

from Bio import SeqIO
for sequence in SeqIO.parse('/content/example_dna.fa', "fasta"):
    print(sequence.id)
    print(sequence.seq)
    print(len(sequence))

"""### Now that we can easily load and manipulate biological sequence data, how can we use it for machine learning or deep learning?
Machine learning and deep learning models require inputs in the form of feature matrices or numerical values. However, our sequence data is still in character or string format. Therefore, the next essential step is to convert these characters into a numerical representation.

There are three common approaches to encode sequence data:

1. Ordinal encoding of DNA sequences

2. One-hot encoding of DNA sequences

3. Treating DNA sequences as a “language” using k-mer counting

### Ordinal Encoding of DNA Sequence Data
In ordinal encoding, each nucleotide (base) in the DNA sequence is represented by a distinct numerical value. This is a simple and memory-efficient way to convert string-based sequences into numerical format, which can then be fed into machine learning models.

For example, consider the DNA sequence:

"ACGTN"

We can assign ordinal values to each base as follows:

A → 0.25

C → 0.5

G → 0.75

T → 1.0

N → 0.0 (used for unknown or ambiguous bases)

So, the encoded version of "ACGTN" would be: [0.25, 0.5, 0.75, 1.0, 0.0]

This numeric representation preserves some sense of order and allows us to handle unknown bases gracefully.
"""

import numpy as np
import re
def string_to_array(seq_str):
   seq_str = seq_str.lower()
   seq_str = re.sub('[^acgt]', 'n', seq_str)
   seq_str = np.array(list(seq_str))
   return seq_str
# create a label encoder with 'acgnt' alphabet
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(np.array(['a', 'c', 'g', 'n', 't']))

"""And here is a function to encode a DNA sequence string as an ordinal vector. It returns a NumPy array with A=0.25, C=0.50, G=0.75, T=1.00, n=0.00."""

def ordinal_encoder(my_array):
    integer_encoded = label_encoder.transform(my_array)
    float_encoded = integer_encoded.astype(float)
    float_encoded[float_encoded == 0] = 0.25 # A
    float_encoded[float_encoded == 1] = 0.50 # C
    float_encoded[float_encoded == 2] = 0.75 # G
    float_encoded[float_encoded == 4] = 1.00 # T
    float_encoded[float_encoded == 3] = 0.00 # anything else, lets say n
    return float_encoded


#Let’s try it out a simple short sequence:
seq_test = 'TTCAGCCAGTGN'
ordinal_encoder(string_to_array(seq_test))

"""### One-Hot Encoding DNA Sequence
One-hot encoding is a popular method for representing DNA sequences, especially in deep learning applications such as convolutional neural networks (CNNs). It converts each nucleotide into a binary vector where only one element is “hot” (i.e., set to 1) and the rest are 0.

Let’s consider the DNA sequence:

"CGTA"

Each nucleotide is represented as a 4-element binary vector:

C → [0, 1, 0, 0]

G → [0, 0, 1, 0]

T → [0, 0, 0, 1]

A → [1, 0, 0, 0]
"""

from sklearn.preprocessing import OneHotEncoder
import numpy as np
def one_hot_encoder(seq_str):
    int_encoded = label_encoder.transform(seq_str)
    onehot_encoder = OneHotEncoder(dtype=int)
    int_encoded = int_encoded.reshape(len(int_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(int_encoded)
    # Convert the sparse matrix to a dense array before deleting the column
    onehot_encoded = onehot_encoded.toarray()
    # Delete the last column (corresponding to 'n')
    onehot_encoded = np.delete(onehot_encoded, -1, 1)
    return onehot_encoded

#So let’s try it out with a simple short sequence:
seq_test = 'GAATTCTCGAA'
one_hot_encoder(string_to_array(seq_test))

"""### DNA Sequence as a “Language” — k-mer Counting
One limitation of the previous encoding methods is that they don’t inherently produce feature vectors of uniform length, which is essential for feeding data into machine learning or deep learning models. To solve this, we often resort to padding or truncating sequences. But there's another approach inspired by natural language processing: k-mer counting.

DNA and protein sequences can be thought of as a biological language. Just like written language has alphabets, words, sentences, and paragraphs, so too does genomic data:

Nucleotide bases (A, C, G, T) are the alphabet

k-mers (short, fixed-length substrings) are the words

Genes are like sentences

The entire genome is a book

Since this structure closely resembles natural language, it makes sense to apply natural language processing (NLP) techniques to biological sequences.
"""

def Kmers_funct(seq, size):
    return [seq[x:x+size].lower() for x in range(len(seq) - size + 1)]


#So let’s try it out with a simple sequence:
mySeq = 'ACGTACGTGACCTGAGTCAAGT'
Kmers_funct(mySeq, size=5)

"""It returns a list of k-mer “words.” You can then join the “words” into a “sentence”, then apply your favorite natural language processing methods on the “sentences” as you normally would."""

words = Kmers_funct(mySeq, size=6)
joined_sentence = ' '.join(words)
joined_sentence

"""You can tune both the word length and the amount of overlap. This allows you to determine how the DNA sequence information and vocabulary size will be important in your application. For example, if you use words of length 6, and there are 4 letters, you have a vocabulary of size 4096 possible words. You can then go on and create a bag-of-words model like you would in NLP.


Let’s make a couple more “sentences” to make it more interesting.
"""

mySeq1 = 'TCTCACACATGTGCCAATCACTGTCACCC'
mySeq2 = 'GTGCCCAGGTTCAGTGAGTGACACAGGCAG'
sentence1 = ' '.join(Kmers_funct(mySeq1, size=6))
sentence2 = ' '.join(Kmers_funct(mySeq2, size=6))

#Creating the Bag of Words model:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform([joined_sentence, sentence1, sentence2]).toarray()
X

"""Here comes machine learning…


Now that we have learned how to extract feature matrix from the DNA sequence, let us apply our newly acquired knowledge to a real-life machine learning use case.

### Analysis of the Input Data
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import matplotlib.pyplot as plt
# %matplotlib inline

"""### Load human DNA data"""

human_dna = pd.read_table('/content/human.txt')
human_dna.head()

human_dna['class'].value_counts().sort_index().plot.bar()
plt.title("Class distribution of Human DNA")

"""### Load Chimpanzee DNA data"""

chimp_dna = pd.read_table('/content/chimpanzee.txt')
chimp_dna.head()

chimp_dna['class'].value_counts().sort_index().plot.bar()
plt.title("Class distribution of Chimpanzee DNA")

"""### Load Dog DNA data"""

dog_dna = pd.read_table('/content/dog.txt')
dog_dna.head()

dog_dna['class'].value_counts().sort_index().plot.bar()
plt.title("Class distribution of Dog DNA")

"""Now we have all our data loaded, the next step is to convert a sequence of characters into k-mer words, default **size = 6 (hexamers)**. The function **Kmers_funct()** will collect all possible overlapping k-mers of a specified length from any sequence string."""

def Kmers_funct(seq, size=6):
    return [seq[x:x+size].lower() for x in range(len(seq) - size + 1)]

#convert our training data sequences into short overlapping k-mers of length 6.
#Lets do that for each species of data we have using our Kmers_funct function.

human_dna['words'] = human_dna.apply(lambda x: Kmers_funct(x['sequence']), axis=1)
human_dna = human_dna.drop('sequence', axis=1)

chimp_dna['words'] = chimp_dna.apply(lambda x: Kmers_funct(x['sequence']), axis=1)
chimp_dna = chimp_dna.drop('sequence', axis=1)

dog_dna['words'] = dog_dna.apply(lambda x: Kmers_funct(x['sequence']), axis=1)
dog_dna = dog_dna.drop('sequence', axis=1)

"""The DNA sequence is changed to lowercase, divided into all possible k-mer words of length 6, and ready for the next step."""

human_dna.head()

"""We need to now convert the lists of k-mers for each gene into string sentences of words that can be used to create the Bag of Words model. We will make a target variable y to hold the class labels."""

human_texts = list(human_dna['words'])
for item in range(len(human_texts)):
    human_texts[item] = ' '.join(human_texts[item])
#separate labels
y_human = human_dna.iloc[:, 0].values # y_human for human_dna

"""Now let's do the same for chimp and dog."""

chimp_texts = list(chimp_dna['words'])
for item in range(len(chimp_texts)):
    chimp_texts[item] = ' '.join(chimp_texts[item])
#separate labels
y_chim = chimp_dna.iloc[:, 0].values # y_chim for chimp_dna

dog_texts = list(dog_dna['words'])
for item in range(len(dog_texts)):
    dog_texts[item] = ' '.join(dog_texts[item])
#separate labels
y_dog = dog_dna.iloc[:, 0].values  # y_dog for dog_dna

y_human

y_chim

y_dog

"""So the target variable contains an array of class values.

Creating the Bag of Words model using CountVectorizer(). This is equivalent to k-mer counting. The n-gram size of 4 was previously determined by testing.

Convert our k-mer words into uniform length numerical vectors that represent counts for every k-mer in the vocabulary:
"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(4,4)) #The n-gram size of 4 is previously determined by testing
X = cv.fit_transform(human_texts)
X_chimp = cv.transform(chimp_texts)
X_dog = cv.transform(dog_texts)

print(X.shape)
print(X_chimp.shape)
print(X_dog.shape)

"""## Classification Models
Classification is a task that requires the use of machine learning algorithms that learn how to assign a class label to examples from the problem domain. An easy to understand example is classifying emails as “spam” or “not spam.”

There are many different types of classification tasks that you may encounter in machine learning and specialized approaches to modeling that may be used for each.

Here I am going to use these six algorithms and by checking the accuracy score I'll find out the perfect model.

* **Logistic Regression** : Logistic regression is a statistical model that in its basic form uses a logistic function to model a binary dependent variable, although many more complex extensions exist. In regression analysis, logistic regression (or logit regression) is estimating the parameters of a logistic model (a form of binary regression).
  
  
* **Decision Tree Classifier** : Decision Tree is a Supervised learning technique that can be used for both classification and Regression problems, but mostly it is preferred for solving Classification problems. It is a tree-structured classifier, where internal nodes represent the features of a dataset, branches represent the decision rules and each leaf node represents the outcome.
  
  
* **Random Forest Classifier** : Random Forest is a popular machine learning algorithm that belongs to the supervised learning technique. It can be used for both Classification and Regression problems in ML. It is based on the concept of ensemble learning, which is a process of combining multiple classifiers to solve a complex problem and to improve the performance of the model.
  
  
* **Naive Bayes** : This method is expected to be called several times consecutively on different chunks of a dataset so as to implement out-of-core or online learning. This is especially useful when the whole dataset is too big to fit in memory at once. This method has some performance and numerical stability overhead, hence it is better to call partial_fit on chunks of data that are as large as possible (as long as fitting in the memory budget) to hide the overhead.
  
  
* **KNN algorithm** : K-Nearest Neighbour is one of the simplest Machine Learning algorithms based on Supervised Learning technique. K-NN algorithm assumes the similarity between the new case/data and available cases and put the new case into the category that is most similar to the available categories. K-NN algorithm stores all the available data and classifies a new data point based on the similarity. This means when new data appears then it can be easily classified into a well suite category by using K- NN algorithm.
  
  
* **Support Vector Machine Algorithm** : Support Vector Machine or SVM is one of the most popular Supervised Learning algorithms, which is used for Classification as well as Regression problems. However, primarily, it is used for Classification problems in Machine Learning. The goal of the SVM algorithm is to create the best line or decision boundary that can segregate n-dimensional space into classes so that we can easily put the new data point in the correct category in the future. This best decision boundary is called a hyperplane.

So, for humans we have **4380** genes converted into uniform length feature vectors of 4-gram k-mer (length 6) counts. For chimp and dog, we have the same number of features with **1682** and **820** genes respectively.


So now that we know how to transform our DNA sequences into uniform length numerical vectors in the form of k-mer counts and ngrams, we can now go ahead and build a classification model that can predict the DNA sequence function based only on the sequence itself.


Here I will use the human data to train the model, holding out 20% of the human data to test the model. Then we can challenge the model’s generalizability by trying to predict sequence function in other species (the chimpanzee and dog).


Next, train/test split human dataset and build several classifier.


You might want to do some parameter tuning and build a model with different ngram sizes, here I’ll go ahead with an ngram size of 4 and a model alpha of 0.1.

<a id="train-test-split"></a>
**Training and Testing Dataset Spliting using the `train_test_split`**
  
  * Immporting the library from the sklearn.model_selection
  * Split the dataset into 80:20 ratio
  * x_train and y_train are the trainning datasets
  * x_test and y_test are the testing datasets
  * After the spliting of the datasets the model is ready to be prepared!
"""

# Splitting the human dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y_human,
                                                    test_size = 0.20,
                                                    random_state=42)

"""We will create a multinomial naive Bayes classifier. I previously did some parameter tuning and found the ngram size of 4 (reflected in the Countvectorizer() instance) and a model alpha of 0.1 did the best. Just to keep it simple I won't show that code here.

## Classification Models based on `Human DNA Data`

### Naive Bayes [Multinomial Naive Bayes] Algorithm
"""

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB(alpha=0.1)
classifier.fit(X_train, y_train)

"""#Now let's make predictions on the human hold out test set and see how it performes on unseen data."""

y_pred = classifier.predict(X_test)

"""Okay, so let's look at some model performce metrics like the confusion matrix, accuracy, precision, recall and f1 score. We are getting really good results on our unseen data, so it looks like our model did not overfit to the training data. In a real project I would go back and sample many more train test splits since we have a relatively small data set."""

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_test, name='Actual'), pd.Series(y_pred, name='Predicted')))
def get_metrics(y_test, y_predicted):
    accuracy = accuracy_score(y_test, y_predicted)
    precision = precision_score(y_test, y_predicted, average='weighted')
    recall = recall_score(y_test, y_predicted, average='weighted')
    f1 = f1_score(y_test, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_test, y_pred)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Random Forest Classifier Algorithm"""

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_test, name='Actual'), pd.Series(y_pred, name='Predicted')))
def get_metrics(y_test, y_predicted):
    accuracy = accuracy_score(y_test, y_predicted)
    precision = precision_score(y_test, y_predicted, average='weighted')
    recall = recall_score(y_test, y_predicted, average='weighted')
    f1 = f1_score(y_test, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_test, y_pred)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### K-Nearest Neighbouring Classifier"""

from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_test, name='Actual'), pd.Series(y_pred, name='Predicted')))
def get_metrics(y_test, y_predicted):
    accuracy = accuracy_score(y_test, y_predicted)
    precision = precision_score(y_test, y_predicted, average='weighted')
    recall = recall_score(y_test, y_predicted, average='weighted')
    f1 = f1_score(y_test, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_test, y_pred)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Decision Tree Classifier Algorithm"""

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

dtc.fit(X_train, y_train)

y_pred = dtc.predict(X_test)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_test, name='Actual'), pd.Series(y_pred, name='Predicted')))
def get_metrics(y_test, y_predicted):
    accuracy = accuracy_score(y_test, y_predicted)
    precision = precision_score(y_test, y_predicted, average='weighted')
    recall = recall_score(y_test, y_predicted, average='weighted')
    f1 = f1_score(y_test, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_test, y_pred)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Model Comparison on `Human DNA Dataset`

I have deployed four classification algorithms for the Human DNA Dataset. Now let's check the accuracy of the models and find out which model is highly efficient!

|Name of the model|Accuracy Score|
|:---:|:---:|
|Multinomial Naive Bayes Algorithm|0.98|
|Random Forest Classifier|0.92|
|Decision Tree Classifier|0.82|
|K-Nearest Neighbours Classifier|0.82|

**It is clearly visible that Multinomial Naive Bayes algorithm is perfectly suited for the Human DNA Dataset with an accuracy of more than 98%!**

-------------

## Classification Models based on `Chimpanzee DNA Data`

<a id="train-test-split"></a>
**Training and Testing Dataset Spliting using the `train_test_split`**
  
  * Immporting the library from the sklearn.model_selection
  * Split the dataset into 80:20 ratio
  * x_train and y_train are the trainning datasets
  * x_test and y_test are the testing datasets
  * After the spliting of the datasets the model is ready to be prepared!
"""

# Splitting the human dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_trainc, X_testc, y_trainc, y_testc = train_test_split(X_chimp,
                                                    y_chim,
                                                    test_size = 0.20,
                                                    random_state=42)

"""### Naive Bayes [Multinomial Naive Bayes] Algorithm"""

from sklearn.naive_bayes import MultinomialNB
classifier_c = MultinomialNB(alpha=0.1)
classifier_c.fit(X_trainc, y_trainc)

y_predc = classifier_c.predict(X_testc)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testc, name='Actual'), pd.Series(y_predc, name='Predicted')))
def get_metrics(y_testc, y_predicted):
    accuracy = accuracy_score(y_testc, y_predicted)
    precision = precision_score(y_testc, y_predicted, average='weighted')
    recall = recall_score(y_testc, y_predicted, average='weighted')
    f1 = f1_score(y_testc, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testc, y_predc)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Random Forest Classifier"""

rfc_c = RandomForestClassifier()
rfc_c.fit(X_trainc, y_trainc)

y_predc = rfc_c.predict(X_testc)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testc, name='Actual'), pd.Series(y_predc, name='Predicted')))
def get_metrics(y_testc, y_predicted):
    accuracy = accuracy_score(y_testc, y_predicted)
    precision = precision_score(y_testc, y_predicted, average='weighted')
    recall = recall_score(y_testc, y_predicted, average='weighted')
    f1 = f1_score(y_testc, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testc, y_predc)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Decision Tree Classifier"""

dtc_c = DecisionTreeClassifier()
dtc_c.fit(X_trainc, y_trainc)

y_predc = dtc_c.predict(X_testc)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testc, name='Actual'), pd.Series(y_predc, name='Predicted')))
def get_metrics(y_testc, y_predicted):
    accuracy = accuracy_score(y_testc, y_predicted)
    precision = precision_score(y_testc, y_predicted, average='weighted')
    recall = recall_score(y_testc, y_predicted, average='weighted')
    f1 = f1_score(y_testc, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testc, y_predc)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### K-Nearest Neighbouring Algorithm"""

knn_c = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )
knn_c.fit(X_trainc, y_trainc)

y_predc = knn_c.predict(X_testc)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testc, name='Actual'), pd.Series(y_predc, name='Predicted')))
def get_metrics(y_testc, y_predicted):
    accuracy = accuracy_score(y_testc, y_predicted)
    precision = precision_score(y_testc, y_predicted, average='weighted')
    recall = recall_score(y_testc, y_predicted, average='weighted')
    f1 = f1_score(y_testc, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testc, y_predc)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Model Comparison on `Chimpanzee DNA Dataset`

I have deployed four classification algorithms for the Chimpanzee DNA Dataset. Now let's check the accuracy of the models and find out which model is highly efficient!

|Name of the model|Accuracy Score|
|:---:|:---:|
|Multinomial Naive Bayes Algorithm|0.91|
|Random Forest Classifier|0.85|
|Decision Tree Classifier|0.77|
|K-Nearest Neighbours Classifier|0.68|

**It is clearly visible that Multinomial Naive Bayes algorithm is perfectly suited for the Human DNA Dataset with an accuracy of more than 91%!**





-----------

## Classification Models based on `Dog DNA Data`

**Training and Testing Dataset Spliting using the `train_test_split`**
  
  * Immporting the library from the sklearn.model_selection
  * Split the dataset into 80:20 ratio
  * x_train and y_train are the trainning datasets
  * x_test and y_test are the testing datasets
  * After the spliting of the datasets the model is ready to be prepared!
"""

# Splitting the human dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_traind, X_testd, y_traind, y_testd = train_test_split(X_dog,
                                                    y_dog,
                                                    test_size = 0.20,
                                                    random_state=42)

"""### Naive Bayes [Multinomial Naive Bayes] Algorithm"""

classifier_d = MultinomialNB(alpha=0.1)
classifier_d.fit(X_traind, y_traind)

y_predd = classifier_d.predict(X_testd)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testd, name='Actual'), pd.Series(y_predd, name='Predicted')))
def get_metrics(y_testd, y_predicted):
    accuracy = accuracy_score(y_testd, y_predicted)
    precision = precision_score(y_testd, y_predicted, average='weighted')
    recall = recall_score(y_testd, y_predicted, average='weighted')
    f1 = f1_score(y_testd, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testd, y_predd)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Decision Tree Classifier"""

dtc_d = DecisionTreeClassifier()
dtc_d.fit(X_traind, y_traind)

y_predd = dtc_d.predict(X_testd)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testd, name='Actual'), pd.Series(y_predd, name='Predicted')))
def get_metrics(y_testd, y_predicted):
    accuracy = accuracy_score(y_testd, y_predicted)
    precision = precision_score(y_testd, y_predicted, average='weighted')
    recall = recall_score(y_testd, y_predicted, average='weighted')
    f1 = f1_score(y_testd, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testd, y_predd)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Random Forest Classifier"""

rfc_d = RandomForestClassifier()
rfc_d.fit(X_traind, y_traind)

y_predd = rfc_d.predict(X_testd)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testd, name='Actual'), pd.Series(y_predd, name='Predicted')))
def get_metrics(y_testd, y_predicted):
    accuracy = accuracy_score(y_testd, y_predicted)
    precision = precision_score(y_testd, y_predicted, average='weighted')
    recall = recall_score(y_testd, y_predicted, average='weighted')
    f1 = f1_score(y_testd, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testd, y_predd)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### K-Nearest Neighbouring Algorithms"""

knn_d = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )
knn_d.fit(X_traind, y_traind)

y_predd = knn_d.predict(X_testd)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Confusion matrix for predictions on human test DNA sequence\n")
print(pd.crosstab(pd.Series(y_testd, name='Actual'), pd.Series(y_predd, name='Predicted')))
def get_metrics(y_testd, y_predicted):
    accuracy = accuracy_score(y_testd, y_predicted)
    precision = precision_score(y_testd, y_predicted, average='weighted')
    recall = recall_score(y_testd, y_predicted, average='weighted')
    f1 = f1_score(y_testd, y_predicted, average='weighted')
    return accuracy, precision, recall, f1
accuracy, precision, recall, f1 = get_metrics(y_testd, y_predd)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""### Model Comparison on `Dog DNA Dataset`

I have deployed four classification algorithms for the Chimpanzee DNA Dataset. Now let's check the accuracy of the models and find out which model is highly efficient!

|Name of the model|Accuracy Score|
|:---:|:---:|
|Multinomial Naive Bayes Algorithm|0.69|
|Random Forest Classifier|0.59|
|Decision Tree Classifier|0.51|
|K-Nearest Neighbours Classifier|0.32|

**It is clearly visible that Multinomial Naive Bayes algorithm is perfectly suited for the Human DNA Dataset with an accuracy of more than 69%!**

------------------------------

### Make this classification model more interesting!!

For 3 different datasets I have deployed four models for each of the datasets. But among all those deployed models, the model which is trained using the Human Dataset, is the best model. The Multinomial Naive Bayes Algorithm on the Human Dataset is the fitted algorithm.

|Name of the model|Accuracy Score|
|:---:|:---:|
|Multinomial Naive Bayes Algorithm on Human dataset|0.98|
|Multinomial Naive Bayes Algorithm on Chimpanzee dataset|0.91|
|Multinomial Naive Bayes Algorithm on dog dataset|0.69|

As the model trained on the human dataset is having higher accuracy, so I choose that model for further proceedings!

Now let's make something different with this highly fitted algorithm.

1. **Predicting Chimpanzee DNA using the Multinomial Naive Bayes (Human Model)**
2. **Predicting Dog DNA using the Multinomial Naive Bayes (Human Model)**

### Predicting Chimpanzee DNA using the Multinomial Naive Bayes (Human Model)

Now for the real test. Let's see how our model perfoms on the DNA sequences from other species. First we'll try the Chimpanzee, which we would expect to be very similar to human. Then we will try man's (and woman's) best friend, the Dog DNA sequences.
"""

# Predicting the chimp, dog sequences
y_pred_chimp = classifier.predict(X_chimp)

# performance on chimpanzee genes
print("Confusion matrix for predictions on Chimpanzee test DNA sequence\n")
print(pd.crosstab(pd.Series(y_chim, name='Actual'), pd.Series(y_pred_chimp, name='Predicted')))
accuracy, precision, recall, f1 = get_metrics(y_chim, y_pred_chimp)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""Let us now do predictions on Dog test DNA sequence.

### Predicting Dog DNA using the Multinomial Naive Bayes (Human Model)
"""

y_pred_dog = classifier.predict(X_dog)

# performance on dog genes
print("Confusion matrix for predictions on Dog test DNA sequence\n")
print(pd.crosstab(pd.Series(y_dog, name='Actual'), pd.Series(y_pred_dog, name='Predicted')))
accuracy, precision, recall, f1 = get_metrics(y_dog, y_pred_dog)
print("accuracy = %.3f \nprecision = %.3f \nrecall = %.3f \nf1 = %.3f" % (accuracy, precision, recall, f1))

"""------------"""